import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Aayush Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <h1 className="text-blue-500">Yo</h1>
    </div>
  );
};

export default Home;
